### ISSUE TITLE
能否兼容下多看？

### ISSUE THREAD

**Issue by a78993992** [cnwxi/epub_tool#1]
先感谢分享，本人是个代码小白，遇到了些问题，混淆文件名直接将【多看】兼容的~slim文件也给混淆进去了，另外当文件过多时，很多css样式和文件章节都会缺失，因本人能力有限，找不到哪里出错

**Comment by cnwxi** [comment]
你好，前者确实没有考虑到。后者你能在附件或者我首页邮件发一下文件吗？

**Comment by a78993992** [comment]
稍等一下，另外我刚才测试了一下，epub2的目录好像有问题，我把文件通过邮箱发你

**Comment by a78993992** [comment]
> 好，之前确实没有考虑到。你可以在附件或者我首页发邮件发一下文件吗？

稍等一下，另外我刚才测试了一下，epub2的目录好像有问题，我把文件通过邮箱发你

**Comment by cnwxi** [comment]
Github已更新，使用阡陌居 如若北音 《【多看全屏版】《道诡异仙》（精校全本+番外）》已加密epub测试。
[【多看全屏版】《道诡异仙》（精校全本+番外）反、混淆.zip](https://github.com/cnwxi/epub_tool/files/15256607/%2B.zip)
[【多看全屏版】《道诡异仙》（精校全本+番外）原文件.zip](https://github.com/cnwxi/epub_tool/files/15256608/%2B.zip)
