### ISSUE TITLE
请问这种文件名如何处理？

### ISSUE THREAD

**Issue by heartnn** [cnwxi/epub_tool#10]
![sshot-1](https://github.com/user-attachments/assets/0b9cded1-9896-45b8-acb9-3c2706056947)
试了一下目前的版本似乎不行。

**Comment by cnwxi** [comment]
你得发原文件，反混淆不是单看这里来的

**Comment by heartnn** [comment]
[test.zip](https://github.com/user-attachments/files/16573232/test.zip)

**Comment by cnwxi** [comment]
## 文件问题
看了你的原文件，content.opf文件里有几个问题：
- manifest内
1. 删去最外层的\<id\>标签
![image](https://github.com/user-attachments/assets/b1c3f92f-8c21-483a-9f49-4c95378e72f6)
2. 同样的问题，删去最外层\<uid\>标签。其次和上一条内容似乎一致，也可以直接删除。
![image](https://github.com/user-attachments/assets/04d3da92-a3c3-4d56-9db3-3a6d591c595d)
补充：好像这两条没有用，可以考虑直接删除
- guide内
1. 没有对应id的文件，请直接删除选中的段落。
![image](https://github.com/user-attachments/assets/4148d7c1-1aad-4fd6-b093-9515859a1c56)
## 修改文件后结果
修改完成后的反混淆文件使用sigil打开如下：
![image](https://github.com/user-attachments/assets/4ab74d9c-ca19-4021-9d3f-59c349450a07)

反混淆后文件如下，请直接解压缩。
[test.zip](https://github.com/user-attachments/files/16573592/test.zip)
## 怎么修改文件
使用WinRAR之类的解压缩软件直接预览epub文件，或使用其他手段打开epub文件中content.opf，修改此文件并更新到原epub中。

**Comment by heartnn** [comment]
OK明白了，感谢大佬

**Comment by cnwxi** [comment]
小事，能解决问题就行。
