### ISSUE TITLE
希望支持无交互运行

### ISSUE THREAD

**Issue by laymanal** [cnwxi/epub_tool#11]
一些优化建议，按代码量排序^^

1. 处理完后显示“请按回车键继续，或输入'e'退出：”这个步骤是多余的，可以直接跳转到下一步。
2. 希望支持无交互运行，这样通过命令行调用，就可以批量处理了。
3. 当然如果程序直接支持批量处理就更好了。

**Comment by cnwxi** [comment]
合理的改进意见，考虑后续更新。








Xiangyu&nbsp;Wang
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月28日(周三) 晚上7:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cnwxi/epub_tool] 希望支持无交互运行 (Issue #11)




 
一些优化建议，按代码量排序^^
  
处理完后显示“请按回车键继续，或输入'e'退出：”这个步骤是多余的，可以直接跳转到下一步。
 
希望支持无交互运行，这样通过命令行调用，就可以批量处理了。
 
当然如果程序直接支持批量处理就更好了。

**Comment by cnwxi** [comment]
> 一些优化建议，按代码量排序^^
> 
> 1. 处理完后显示“请按回车键继续，或输入'e'退出：”这个步骤是多余的，可以直接跳转到下一步。
> 2. 希望支持无交互运行，这样通过命令行调用，就可以批量处理了。
> 3. 当然如果程序直接支持批量处理就更好了。

已更新，请测试。

**Comment by cnwxi** [comment]
> 程序棒极了，谢谢大佬这么及时的更新。 我的书库有严谨的文件夹结构，不方便移动，可否支持子目录遍历。 另外如果有反混淆时跳过未混淆文件，混淆时跳过（本程序）已混淆文件的功能就完美了。

最好还是按需执行，短时间应该不会去考虑处理你说的这种情况。

**Comment by laymanal** [comment]
> > 程序棒极了，谢谢大佬这么及时的更新。 我的书库有严谨的文件夹结构，不方便移动，可否支持子目录遍历。 另外如果有反混淆时跳过未混淆文件，混淆时跳过（本程序）已混淆文件的功能就完美了。
> 
> 最好还是按需执行，短时间应该不会去考虑处理你说的这种情况。

没关系，这样已经很好了。

**Comment by cnwxi** [comment]
> 程序棒极了，谢谢大佬这么及时的更新。 我的书库有严谨的文件夹结构，不方便移动，可否支持子目录遍历，输出目录中的结果文件也能保持目录结构。 另外如果有反混淆时跳过未混淆文件，混淆时跳过（本程序）已混淆文件的功能就完美了。

已支持子目录遍历。

**Comment by laymanal** [comment]
Great job 🎉

**Comment by laymanal** [comment]
> 已支持子目录遍历，已重新编译可执行文件，请下载覆盖。

Great job 🎉
批量处理带来的新需求，希望可以输出log，主要是 ERROR, WARN，虽然现在用管道重定向的方式可以得到未筛选的log文件，但有的 ERROR 捕捉不到，要找有问题的epub挺麻烦的。
Sorry 提了很多需求😅

**Comment by cnwxi** [comment]
笑死。快到了。

**Comment by cnwxi** [comment]
> > 已支持子目录遍历，已重新编译可执行文件，请下载覆盖。
> 
> Great job 🎉 程序出错中断，希望可以输出log，主要是 ERROR, WARN，虽然现在用管道重定向的方式可以得到未筛选的log文件，但有的 ERROR 捕捉不到，要找有问题的epub挺麻烦的。 Sorry 提了很多需求😅

已更新。

**Comment by laymanal** [comment]
> 已更新。早上起来又改了一下，应该是没啥大问题了。

大佬没得说是真🐂🍺，等有空的话看看这个文件 [test.zip](https://github.com/user-attachments/files/16792257/test.zip)，应该用其他混淆的，用epub_tool反混淆处理不了。

![屏幕截图 2024-08-29 124359](https://github.com/user-attachments/assets/185e3490-ac4d-4481-a4ce-083fb4c523f2)

![屏幕截图 2024-08-29 125356](https://github.com/user-attachments/assets/f1754b74-eac5-4adf-9bc7-a0ac86415abb)

![屏幕截图 2024-08-29 125154](https://github.com/user-attachments/assets/a2264b8e-a0b6-40f5-90e9-0b744a23a719)

**Comment by cnwxi** [comment]
> > 已更新。早上起来又改了一下，应该是没啥大问题了。
> 
> 大佬没得说是真🐂🍺，等有空的话看看这个文件 [test.zip](https://github.com/user-attachments/files/16792257/test.zip)，应该用其他混淆的，用epub_tool反混淆处理不了。
> 
> ![屏幕截图 2024-08-29 124359](https://private-user-images.githubusercontent.com/1684121/362537901-185e3490-ac4d-4481-a4ce-083fb4c523f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM4OTEsIm5iZiI6MTcyNDkxMzU5MSwicGF0aCI6Ii8xNjg0MTIxLzM2MjUzNzkwMS0xODVlMzQ5MC1hYzRkLTQ0ODEtYTRjZS0wODNmYjRjNTIzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDYzOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBhY2Y0MDE3NWU3YjQ3YThiMmY1OTQ4YTcwZmUwOTk5MzlhNmUyNWQ5M2YyZWIzMTE5MjVlOTEwNjQ0Y2FlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yrcnu0vZzvVtHaDZ3lKPYRAYZ-5t2povy_zUYhoDdlI)
> 
> ![屏幕截图 2024-08-29 125356](https://private-user-images.githubusercontent.com/1684121/362537954-f1754b74-eac5-4adf-9bc7-a0ac86415abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM4OTEsIm5iZiI6MTcyNDkxMzU5MSwicGF0aCI6Ii8xNjg0MTIxLzM2MjUzNzk1NC1mMTc1NGI3NC1lYWM1LTRhZGYtOWJjNy1hMGFjODY0MTVhYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDYzOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDcyYWZlMmU1OGZhMjQ3NzE2ZDgxYmZmZDQ5ZDUxM2MyNWE3ODIwMjQ4ODNlY2EzMzAxNjVmNWZiN2E4YzJiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fKfHHu7uDASu_myqBHgZVPKAg40dfQmsGgJJCr6dNOk)
> 
> ![屏幕截图 2024-08-29 125154](https://private-user-images.githubusercontent.com/1684121/362540098-fa9e7369-3f14-4c9d-b6dc-0945c14fee72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM4OTEsIm5iZiI6MTcyNDkxMzU5MSwicGF0aCI6Ii8xNjg0MTIxLzM2MjU0MDA5OC1mYTllNzM2OS0zZjE0LTRjOWQtYjZkYy0wOTQ1YzE0ZmVlNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDYzOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4ZmZkYjg1NjZkNGM0OGU0N2ZmMmUzNWQxZjEzMDRlYzU2ODUxYmRiMGI4ZmYxZTNiZWNlMjkwYzY5ZWZjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Iwybn9q7LwtUN4tRhRpR27XzBgPtEH6eKtLgFeQ6sYk)

已更新，简单处理了一下。

**Comment by laymanal** [comment]
Perfect!

**Comment by cnwxi** [comment]
> 程序棒极了，谢谢大佬这么及时的更新。 我的书库有严谨的文件夹结构，不方便移动，可否支持子目录遍历，输出目录中的结果文件也能保持目录结构。 另外如果有反混淆时跳过未混淆文件，混淆时跳过（本程序）已混淆文件的功能就完美了。

目前采用判断固定后缀跳过对应操作。

**Comment by cnwxi** [comment]
> 程序棒极了，谢谢大佬这么及时的更新。 我的书库有严谨的文件夹结构，不方便移动，可否支持子目录遍历，输出目录中的结果文件也能保持目录结构。 另外如果有反混淆时跳过未混淆文件，混淆时跳过（本程序）已混淆文件的功能就完美了。

混淆、反混淆跳过，已更新。
