### ISSUE TITLE
希望能搞成Sigil插件

### ISSUE THREAD

**Issue by D33274D7C6** [cnwxi/epub_tool#12]
希望能搞成Sigil插件，Pytho门槛有点高。

**Comment by cnwxi** [comment]
这个搞不了呀，哥们。混淆和反混淆的原理是用文件系统无法识别的特殊字符替换原有文件名，sigil本身就不支持这些特殊字符，做成插件完全不可用啊。
不是有可执行文件么，建议下可执行文件，使用命令行运行。

**Comment by D33274D7C6** [comment]
> 这个搞不了呀，哥们。混淆和反混淆的原理是用文件系统无法识别的特殊字符替换原有文件名，sigil本身就不支持这些特殊字符，做成插件完全不可用啊。 不是有可执行文件么，建议下可执行文件，使用命令行运行。

我看有人搞过用Sigil插件进行混淆和反混淆，以为可以的。不行吗？
不会用命令行，win那个exe打开就闪退，搞不懂咋用。哎，算了吧。反正手机端有能看混淆的，无奈。

**Comment by cnwxi** [comment]
> > 这个搞不了呀，哥们。混淆和反混淆的原理是用文件系统无法识别的特殊字符替换原有文件名，sigil本身就不支持这些特殊字符，做成插件完全不可用啊。 不是有可执行文件么，建议下可执行文件，使用命令行运行。
> 
> 我看有人搞过用Sigil插件进行混淆和反混淆，以为可以的。不行吗？ 不会用命令行，win那个exe打开就闪退，搞不懂咋用。哎，算了吧。反正手机端有能看混淆的，无奈。

用cmd打开，仔细看教程

**Comment by cnwxi** [comment]
> > 这个搞不了呀，哥们。混淆和反混淆的原理是用文件系统无法识别的特殊字符替换原有文件名，sigil本身就不支持这些特殊字符，做成插件完全不可用啊。 不是有可执行文件么，建议下可执行文件，使用命令行运行。
> 
> 我看有人搞过用Sigil插件进行混淆和反混淆，以为可以的。不行吗？ 不会用命令行，win那个exe打开就闪退，搞不懂咋用。哎，算了吧。反正手机端有能看混淆的，无奈。

已更新。

**Comment by D33274D7C6** [comment]
![IMG_20240909_071004](https://github.com/user-attachments/assets/750d1ee9-99a4-4c6f-913a-ca0d5bcceab7)

Traceback (most recent call last):
  File "epub_tool.py", line 7, in <module>
ModuleNotFoundError: No module named 'tqdm'
[PYI-12100:ERROR] Failed to execute script 'epub_tool' due to unhandled exception!

这是为啥啊，我把桌面设置在了D盘，zip解压在桌面、要处理的文件也在桌面。

**Comment by cnwxi** [comment]
> ![IMG_20240909_071004](https://private-user-images.githubusercontent.com/85822722/365472944-750d1ee9-99a4-4c6f-913a-ca0d5bcceab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDEzNjAsIm5iZiI6MTcyNTg0MTA2MCwicGF0aCI6Ii84NTgyMjcyMi8zNjU0NzI5NDQtNzUwZDFlZTktOTlhNC00YzZmLTkxM2EtY2EwZDViY2NlYWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZjQ2NDYxOTY5ZjlkODA2M2M5ZWEyMWQ1NjA5NDVjNzk4ZTkzMDgyMWFiNzU5MGU0M2VjMjA5MzdlZmE1ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PnWE1QInHbnLVFPeFUl1kbTnjn6e8YdKRZbdWc5vdmg)
> 
> Traceback (most recent call last): File "epub_tool.py", line 7, in ModuleNotFoundError: No module named 'tqdm' [PYI-12100:ERROR] Failed to execute script 'epub_tool' due to unhandled exception!
> 
> 这是为啥啊，我把桌面设置在了D盘，zip解压在桌面、要处理的文件也在桌面。

有个依赖忘记打包了，已重新打包可执行程序。

**Comment by D33274D7C6** [comment]
完美，能用了，比某大佬私人的Sigil混淆插件快多了。

虽然大佬似乎不打算搞自动跳过已混淆文件的混淆和已反混淆文件的反混淆（#11）。但基本功能足够使用了，谢谢大佬的更新啦。

**Comment by cnwxi** [comment]
> 完美，能用了，比某大佬私人的Sigil混淆插件快多了。
> 
> 虽然大佬似乎不打算搞自动跳过已混淆文件的混淆和已反混淆文件的反混淆（#11）。但基本功能足够使用了，谢谢大佬的更新啦。

后续有时间再更新一下吧。

**Comment by cnwxi** [comment]
> 完美，能用了，比某大佬私人的Sigil混淆插件快多了。
> 
> 虽然大佬似乎不打算搞自动跳过已混淆文件的混淆和已反混淆文件的反混淆（#11）。但基本功能足够使用了，谢谢大佬的更新啦。

已更新
