### ISSUE TITLE
路径包含引号报错

### ISSUE THREAD

**Issue by laymanal** [cnwxi/epub_tool#14]
一个小bug，只发生在不带参数运行程序时，路径包含引号会报错。我一般偷懒不愿打字时，习惯直接拖放文件。

![屏幕截图 2024-10-24 170147](https://github.com/user-attachments/assets/3db1ccdb-a6ae-4f7c-922a-81cffdb00fb2)

**Comment by cnwxi** [comment]
报错结果显示什么？

**Comment by laymanal** [comment]
> 报错结果显示什么？

输入路径不存在

**Comment by cnwxi** [comment]
ok，明白了

**Comment by cnwxi** [comment]
> 一个小bug，只发生在不带参数运行程序时，路径包含引号会报错。我一般偷懒不愿打字时，习惯直接拖放文件。
> 
> ![屏幕截图 2024-10-24 170147](https://private-user-images.githubusercontent.com/1684121/379697002-3db1ccdb-a6ae-4f7c-922a-81cffdb00fb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjM1ODgsIm5iZiI6MTcyOTc2MzI4OCwicGF0aCI6Ii8xNjg0MTIxLzM3OTY5NzAwMi0zZGIxY2NkYi1hNmFlLTRmN2MtOTIyYS04MWNmZmRiMDBmYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDk0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJkNjg5NzA2NzBlNzA1NTEyMmNjN2RlMTgwYWMyMWE4YjM0NDliYWI3MzQyYWFmZTUxZWU4OWZhNzkzYTg2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gVeoyLX7QKvugK1u8wAwM01_2uesMbB5aNxrMw3eqIs)

<img width="697" alt="截屏2024-10-24 17 48 38" src="https://github.com/user-attachments/assets/82693578-2a35-4fb7-98c7-fc69f733c3b1">
应该是OK了。

**Comment by laymanal** [comment]
好极了
