### ISSUE TITLE
反文件名混淆这文件会闪退，查看解构后的文件里面没有content.opf。

### ISSUE THREAD

**Issue by a70456** [cnwxi/epub_tool#8]
[日本权力结构之谜.zip](https://github.com/user-attachments/files/15804341/default.zip)

**Comment by cnwxi** [comment]
回复你上次在代码提交中问的问题
>非代码问题，文件问题：
正常加密后的opf文件中：
![image](https://github.com/cnwxi/epub_tool/assets/45331556/8320e291-95a3-4ce3-b31f-54521dc569dd)
此文件：
![image](https://github.com/cnwxi/epub_tool/assets/45331556/95535c9d-f11a-4924-99b6-ab65fd8979fc)
修正后：
![image](https://github.com/cnwxi/epub_tool/assets/45331556/61f32fdc-c3c0-4b65-b1ff-d09ed7b20d37)
![image](https://github.com/cnwxi/epub_tool/assets/45331556/c9eb069d-0168-4ca7-9642-afd40a473a47)
请使用winrar之类的压缩工具直接修改原opf文件中关于封面页的引用。
以下为修改后的epub（未反混淆）
[结构之谜.zip](https://github.com/user-attachments/files/15788904/default.zip)

然后是这次的，同样的问题，原文件混淆并不完全
![image](https://github.com/cnwxi/epub_tool/assets/45331556/f307ba03-a15b-45a7-b0b9-0b164a5ac63a)
自行使用WinRAR之类的文件修改原epub中未加密的文件链接
![image](https://github.com/cnwxi/epub_tool/assets/45331556/7ebb9f28-e666-4fbb-80aa-7754d1055dce)
把上面这一段复制替换掉未加密部分。

**Comment by cnwxi** [comment]
已考虑处理此情况，但可能导致处理时间过长，其次特例情况很难覆盖。最新代码已针对此情况进行处理。
